CREATE DATABASE QuanLyBanGiay_DA1_Nhom4
USE QuanLyBanGiay_DA1_Nhom4
GO
-- ChucVu
CREATE TABLE ChucVu(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(50) DEFAULT NULL
)
GO
-- NhanVien
CREATE TABLE NhanVien(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdCV UNIQUEIDENTIFIER,
Ma VARCHAR(20) UNIQUE,
HoTen NVARCHAR(100),
TaiKhoan VARCHAR(MAX) DEFAULT NULL,
MatKhau VARCHAR(MAX) DEFAULT NULL,
Sdt VARCHAR(30) DEFAULT NULL,
Email  VARCHAR(100) DEFAULT NULL,
GioiTinh NVARCHAR(10) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL
)
GO
-- KhachHang
CREATE TABLE KhachHang(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
HoTen NVARCHAR(100),
Sdt VARCHAR(30),
NgaySinh DATE DEFAULT NULL,
DiaChi NVARCHAR(100) DEFAULT NULL,
)
GO
-- SanPham
CREATE TABLE SanPham(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30)
)
GO
-- DeGiay
CREATE TABLE DeGiay(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30)
)
GO
-- MauSac
CREATE TABLE MauSac(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30)
)
GO
-- DongSP
CREATE TABLE DongSP(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(30)
)
GO
-- ChiTietSP
CREATE TABLE ChiTietSP(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdSP UNIQUEIDENTIFIER,
IdDongSP UNIQUEIDENTIFIER,
IdDeGiay UNIQUEIDENTIFIER,
IdMauSac UNIQUEIDENTIFIER,
NgayNhapHang DATE DEFAULT NULL,
DonGia DECIMAL(20,0) DEFAULT 0,
SoLuong INT,
XuatXu NVARCHAR(50) DEFAULT NULL,
KichCo NVARCHAR(20),
TrangThai int DEFAULT 0
)
GO
--SanPhamLoi
CREATE TABLE DoiTra(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdCTSP UNIQUEIDENTIFIER,
IdHD UNIQUEIDENTIFIER,
IdKH UNIQUEIDENTIFIER,
NgayDoi DATE DEFAULT NULL,
SoLuong INT,
LiDoDoi NVARCHAR(50) DEFAULT NULL,
GhiChu NVARCHAR(100) DEFAULT NULL
)
GO

--HoaDon
CREATE TABLE HoaDon(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdKH UNIQUEIDENTIFIER,
IdNV UNIQUEIDENTIFIER,
IdVoucher UNIQUEIDENTIFIER,
Ma VARCHAR(20) UNIQUE,
NgayTao DATE DEFAULT NULL,
NgayThanhToan DATE DEFAULT NULL,
TongTien DECIMAL(20,0) DEFAULT 0,
TongSanPham INT,
TrangThai INT DEFAULT 0
)
GO

-- HoaDonChiTiet
CREATE TABLE HoaDonChiTiet(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IdHoaDon UNIQUEIDENTIFIER,
IdChiTietSP UNIQUEIDENTIFIER,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0
)

-- Voucher
CREATE TABLE Voucher(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
Ma VARCHAR(20) UNIQUE,
Ten NVARCHAR(100),
GiamGia FLOAT,
NgayBatDau DATE DEFAULT NULL,
NgayHetHan DATE DEFAULT NULL,
GhiChu Nvarchar(100) DEFAULT NULL,
TrangThai INT DEFAULT 0
)

GO
--T?O QUAN H? GI?A CÁC B?NG
--NhanVien - ChucVu
ALTER TABLE NhanVien ADD FOREIGN KEY (IdCV) REFERENCES ChucVu(Id)

-- ChiTietSP - SanPham
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdSP) REFERENCES SanPham(Id)
-- ChiTietSP - DongSP
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdDongSP) REFERENCES DongSP(Id)
-- ChiTietSP - DeGiay
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdDeGiay) REFERENCES DeGiay(Id)
-- ChiTietSP - MauSac
ALTER TABLE ChiTietSP ADD FOREIGN KEY(IdMauSac) REFERENCES MauSac(Id)
-- ChiTietSP - NhaCC

-- DoiTra - CTSanPham
ALTER TABLE DoiTra ADD FOREIGN KEY(IdCTSP) REFERENCES ChiTietSP(Id)
-- DoiTra - HoaDon
ALTER TABLE DoiTra ADD FOREIGN KEY(IdHD) REFERENCES HoaDon(Id)
-- DoiTra - KhachHang
ALTER TABLE DoiTra ADD FOREIGN KEY(IdKH) REFERENCES KhachHang(Id)


--HoaDonCT - ChiTietSP
ALTER TABLE HoaDonChiTiet ADD FOREIGN KEY(IdHoaDon) REFERENCES HoaDon(Id)
--HoaDonCT - ChiTietSP
ALTER TABLE HoaDonChiTiet ADD FOREIGN KEY(IdChiTietSP) REFERENCES ChiTietSP(Id)

-- HoaDon - KhachHang
ALTER TABLE HoaDon ADD FOREIGN KEY (IdKH) REFERENCES KhachHang(Id)
-- HoaDon - NhanVien
ALTER TABLE HoaDon ADD FOREIGN KEY (IdNV) REFERENCES NhanVien(Id)
-- HoaDon - Voucher
ALTER TABLE HoaDon ADD FOREIGN KEY (IdVoucher) REFERENCES Voucher(Id)




--**********************************************************************
-- PHÀN INSERT CH?Y RIÊNG NHÉ
-- B?NG NÀO KHÔNG CÓ KHÓA PH? THÌ C? TH? MÀ BÔI ÐEN XONG EXECUTE
-- B?NG NÀO CÓ KHÓA PH? THÌ S?A PHÀN ID Ð? MAPPING V?I B?NG CÒN L?I
--
--
--
--
--
--
--
--
--
--
--
--
--***********************************************************************
--Insert ChucVu
INSERT INTO ChucVu VALUES (NEWID(),'CV01',N'Quản lý')
INSERT INTO ChucVu VALUES (NEWID(),'CV02',N'Nhân viên')
Select * from ChucVu

--Insert NhanVien
Select * from NhanVien
delete from NhanVien
INSERT INTO NhanVien VALUES(NEWID(),'660906E8-778D-4FAC-BCA5-3FBFC3F1F05E','NV01',N'Trần Ðức Bo','nhanvien01','nv01','0989031433','boductran1980@gmail.com',N'Nam','07-06-1999',N'số 3 ngõ 178 Lê Ðức Thọ, Hà Nội')
INSERT INTO NhanVien VALUES(NEWID(),'660906E8-778D-4FAC-BCA5-3FBFC3F1F05E','NV02',N'Nguyễn Hoàng Ðức','nhanvien02','nv02','0970987231','ducnguyenhoang1980@gmail.com',N'Nam','05-09-1980',N'số 20 ngõ 91 Kiều Mai, Hà Nội')
INSERT INTO NhanVien VALUES(NEWID(),'FDA3266F-C8DE-4866-BC72-78DC93BDFE16','QL01',N'Nguyễn Thùy Linh','quanly01','ql01','0970987231','linhttnguyen19770@gmail.com',N'Nữ','04-11-1977',N'số 19 ngõ 20 Hồ Tùng Mậu, Hà Nội')
INSERT INTO NhanVien(Id,IdCV, Ma, HoTen) VALUES(NEWID(),'660906E8-778D-4FAC-BCA5-3FBFC3F1F05E','NV00',N'Tên nhân viên');
--Insert KhachHang
Select * from KhachHang
INSERT INTO KhachHang VALUES(NEWID(),'KH01',N'Nguyễn Công Phượng','0978031456','2003-11-11',N'số 09 ngõ 77 Nhổn, Hà Nội')
INSERT INTO KhachHang VALUES(NEWID(),'KH02',N'Nguyễn Tiến Linh','0989076890','2002-09-12',N'số 29 ngõ 197 Cầu Diễn, Thái Nguyên')
INSERT INTO KhachHang VALUES(NEWID(),'KH03',N'Ðặng Van Lâm','0978031456','2004-10-24',N'số 81 ngõ 104 Nguyên Xá, Hà Nội')
INSERT INTO KhachHang(id, Ma, HoTen, Sdt) VALUES(NEWID(),'KH00',N'Tên khách hàng','(84+)')
--Insert SanPham
Select * from SanPham
INSERT INTO SanPham VALUES (NEWID(),'SP01',N'Adidas Ultra Boost')
INSERT INTO SanPham VALUES (NEWID(),'SP02',N'Adidas Yeezy')
INSERT INTO SanPham VALUES (NEWID(),'SP03',N'Adidas Stan Smith')
INSERT INTO SanPham VALUES (NEWID(),'SP04',N'Adidas NMD')
INSERT INTO SanPham VALUES (NEWID(),'SP05',N'Nike Jordan')
INSERT INTO SanPham VALUES (NEWID(),'SP06',N'Nike Air')
INSERT INTO SanPham VALUES (NEWID(),'SP07',N'Nike Air Max')
INSERT INTO SanPham VALUES (NEWID(),'SP08',N'Nike Cortez')
INSERT INTO SanPham VALUES (NEWID(),'SP09',N'Nike Air Force 1')
INSERT INTO SanPham VALUES (NEWID(),'SP10',N'Converse Chuck Taylor')
INSERT INTO SanPham VALUES (NEWID(),'SP11',N'Converse Chuck Taylor 2')
INSERT INTO SanPham VALUES (NEWID(),'SP12',N'Converse 1970s')


--Insert DeGiay
Select * from DeGiay
INSERT INTO DeGiay VALUES (NEWID(),'DG01',N'Low – Top')
INSERT INTO DeGiay VALUES (NEWID(),'DG02',N'Mid – Top')
INSERT INTO DeGiay VALUES (NEWID(),'DG03',N'High – Top')

--Insert MauSac
Select * from MauSac
INSERT INTO MauSac VALUES (NEWID(),'MS01',N'Ðen')
INSERT INTO MauSac VALUES (NEWID(),'MS02',N'Trắng')
INSERT INTO MauSac VALUES (NEWID(),'MS03',N'Nâu')
INSERT INTO MauSac VALUES (NEWID(),'MS04',N'Hồng')
INSERT INTO MauSac VALUES (NEWID(),'MS05',N'Ðỏ')
INSERT INTO MauSac VALUES (NEWID(),'MS06',N'Xanh')
--Insert DongSanPham
Select * from DongSP
INSERT INTO DongSP VALUES (NEWID(),'DSP01',N'Adidas')
INSERT INTO DongSP VALUES (NEWID(),'DSP02',N'Nike')
INSERT INTO DongSP VALUES (NEWID(),'DSP03',N'Converse')


--Insert ChiTietSanPham
Select * from SanPham
Select * from DongSP
Select * from DeGiay
Select * from MauSac

select * from ChiTietSP

Insert into ChiTietSP values(NEWID(),'87F30D29-98FD-4FA1-86DE-02D3F72D572B','D012D95C-1E4C-4DC9-84DB-43C33C7BD5EE','EAD22E8F-479F-4902-A4FB-322B11D701E1','1695C53A-FDEB-43C6-A534-40A48FD01B80','10-10-2022',250000,26,N'Việt Nam','40',0)

--Insert Voucher
select * from Voucher
Insert into Voucher values(NEWID(),'VC01',N'Giảm giá dịp Noel',0.95,'03-12-2022','10-10-2022',N'Áp dụng toàn bộ sản phẩm',0)
--Insert HoaDon
Select * from KhachHang
Select * from NhanVien
Select * from HoaDon
Insert into HoaDon values(NEWID(),'F26542FD-47FB-41DD-AA98-15B7DA5E3111','7730B4DF-316B-47F0-B46C-66F51CE93875','5F079824-6D72-4AFD-9489-72D9A3C8C3E9','HD01','10-10-2022','10-10-2022',250000,1,0)

--Insert DoiTra

Select * from ChiTietSP
Select * from HoaDon
select * from KhachHang
select * from DoiTra
Insert into DoiTra values(NEWID(),'C1134ECA-3C5A-4C64-AC6F-0C7C7FC328BA','D241CBE5-7786-4613-AD99-1D0698CA3D18','FEAC7216-3C0D-4371-8885-CD657E6205F5','2022-12-05',1,N'Bị lỗi',N'Sản phẩm bị lỗi')


--Insert HDCT
Select * from HoaDonChiTiet
Select * from HoaDon
select * from ChiTietSP
Insert into HoaDonChiTiet values(NEWID(),'8EF6AF9B-1B44-4AF2-AC9A-5F72770EF90C','702141DD-4D7A-4545-AC89-116CC5806813',1,250000)





